change all

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,33 +1,86 @@
-#!/bin/sh
+#!/bin/bash
+# usage: bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -eu
+set -eo pipefail
 
+BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
+buildpack="$(cd -P "$(dirname "$0")" && pwd)"
 
-KEYCLOAK_VERSION=`cat ./bin/version`
-KEYCLOAK_DIR="$1/target"
-KEYCLOAK_ZIP="$CACHE_DIR/keycloak-$KEYCLOAK_VERSION.zip"
-KEYCLOAK_URL="https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.zip"
+source "${buildpack}/common.sh"
 
-mkdir -p $KEYCLOAK_DIR
-
-if [ -f "$KEYCLOAK_ZIP" ]; then
-    echo "-----> Using cached Keycloak archive"
-else
-    echo "-----> Downloading Keycloak from $KEYCLOAK_URL to $KEYCLOAK_ZIP"
-    curl -s --retry 3 -o $KEYCLOAK_ZIP -L $KEYCLOAK_URL
+if [ -n "$BUILDPACK_DEBUG" ]; then
+  set -x
 fi
-echo "done"
 
-echo "-----> Unzipping Keycloak"
-unzip $KEYCLOAK_ZIP -d $KEYCLOAK_DIR > /dev/null
-mv "$KEYCLOAK_DIR/keycloak-$KEYCLOAK_VERSION" "$KEYCLOAK_DIR/keycloak"
-rm $KEYCLOAK_ZIP
-echo "done"
+KEYCLOAK_PATH="$BUILD_DIR/keycloak"
+TMP_PATH="$BUILD_DIR/tmp"
+mkdir -p "${BUILD_DIR}/bin" "${CACHE_DIR}/dist" "${TMP_PATH}"
+export PATH="$BUILD_DIR/bin:$PATH"
 
-echo "-----> Downloading postgres jdbc driver"
-JDBC_POSTGRES_VERSION=42.2.5
-POSTGRES_DIR="$KEYCLOAK_DIR/keycloak/modules/system/layers/base/org/postgresql/jdbc/main"
-mkdir -p $POSTGRES_DIR
-curl -s -L https://repo1.maven.org/maven2/org/postgresql/postgresql/$JDBC_POSTGRES_VERSION/postgresql-$JDBC_POSTGRES_VERSION.jar > "$POSTGRES_DIR/postgres-jdbc.jar"
-cp tools/databases/postgres/module.xml $POSTGRES_DIR
+STACK="${STACK:-scalingo-20}"
+
+start "Install Keycloak"
+
+install_jre
+
+if [[ -f "$ENV_DIR/KEYCLOAK_VERSION" ]]; then
+  KEYCLOAK_VERSION=$(cat "$ENV_DIR/KEYCLOAK_VERSION")
+else
+  KEYCLOAK_VERSION="latest"
+fi
+
+if [[ $KEYCLOAK_VERSION == "latest" ]]; then
+  KEYCLOAK_VERSION=$(fetch_github_latest_release "${TMP_PATH}" "keycloak/keycloak")
+fi
+
+if [ ! -d "${KEYCLOAK_PATH}" ]; then
+  if [[ -n "${KEYCLOAK_VERSION}" ]]; then
+    fetch_keycloak_dist "${KEYCLOAK_VERSION}" "${TMP_PATH}" | indent
+    mv "${TMP_PATH}/keycloak-${KEYCLOAK_VERSION}" "${KEYCLOAK_PATH}"
+  fi
+else
+  warn "Keycloak already installed"
+fi
+info "Using keycloak version: ${KEYCLOAK_VERSION}" | indent
+finished
+
+
+step "Adding providers"
+if [[ -f "${ENV_DIR}/KEYCLOAK_PROVIDERS" ]]; then
+  KEYCLOAK_PROVIDERS=$(cat "${ENV_DIR}/KEYCLOAK_PROVIDERS")
+  IFS=','
+  read -ra PROVIDERS <<< "${KEYCLOAK_PROVIDERS}"
+  for PROVIDER_REPO in "${PROVIDERS[@]}"; do   
+    PROVIDER_NAME=$(get_provider_name "${PROVIDER_REPO}")
+    PROVIDER_VERSION=$(fetch_github_latest_release "${TMP_PATH}" "${PROVIDER_REPO}")
+    start "Add provider ${PROVIDER_NAME} ${PROVIDER_VERSION}"
+    if [[ ! "${PROVIDER_VERSION}" == "" ]]; then
+      fetch_provider_dist "${PROVIDER_REPO}" "${PROVIDER_VERSION}" "${TMP_PATH}" "${KEYCLOAK_PATH}" | indent
+      finished
+    else
+      warn "unable to fetch ${PROVIDER_REPO} latest release"
+    fi
+  done
+  IFS=' ' 
+fi
+
+step "Adding templates"
+if [[ -f "${ENV_DIR}/KEYCLOAK_TEMPLATES_DIR" ]]; then
+  KEYCLOAK_TEMPLATES_DIR=$(cat "${ENV_DIR}/KEYCLOAK_TEMPLATES_DIR")
+  add_templates "${KEYCLOAK_TEMPLATES_DIR}" "${KEYCLOAK_PATH}"
+fi
+
+if [[ -f "$ENV_DIR/KC_DB" ]]; then
+  KC_DB=$(cat "$ENV_DIR/KC_DB")
+else
+  KC_DB="postgres"
+fi
+step "Configuring the ${KC_DB} vendor"
+"${KEYCLOAK_PATH}/bin/kc.sh" build --db ${KC_DB}
+
+step "Cleaning up tmp files"
+rm -rf "${TMP_PATH}"
+
+finished
